---
title: "Inventory maps"
author: "Jens Daniel Müller and Donghe Zhu"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r parent, child = "/nfs/kryo/work/jenmueller/emlr_cant/utilities/setup.Rmd"}
# this chunk runs the code stored in setup.Rmd
# if required, please refer to instructions given here:
# https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html
```

```{r read_params_local, include = FALSE}

Version_ID <- "v_XXX_118"

```

```{r define_paths, include = FALSE}

path_model <-
  paste(path_root, "/model/", sep = "")

path_preprocessing    <-
  paste(path_model, "preprocessing/", sep = "")

params_local     <-
  read_rds(
    paste(
      "/home/donzhu/Thesis/emlr_cant/model/emlr_mod_v_118/data/auxillary/",
      "params_local.rds",
      sep = ""
    )
  )

path_version_data     <-
  paste(path_model,
        Version_ID,
        "/data/",
        sep = "")

path_version_figures  <-
  paste(path_model,
        Version_ID,
        "/figures/",
        sep = "")
```


```{r load_libraries_specific, include = FALSE}
library(scales)
library(marelac)
library(gt)
```


# Inventory maps

## Cant - positive only

```{r read_cant_inv_file, eval=FALSE}

cant_inv_JDM <-
  read_csv(paste(path_version_data,
                 "cant_inv.csv",
                 sep = ""))

cant_inv_M <-
  read_csv(paste(path_version_data,
                  "cant_inv_M.csv", sep = ""))

```

```{r join_M_and_JDM_inventories, eval=FALSE}

# add estimate label
cant_inv_long <- bind_rows(cant_inv_JDM %>%  mutate(estimate = "JDM"),
                           cant_inv_M %>%  mutate(estimate = "M"))

# pivot to wide format
cant_inv_wide <- cant_inv_long %>%
  pivot_wider(names_from = estimate, values_from = cant_pos_inv:cant_inv) %>%
  drop_na()

# calculate offset
cant_inv_wide <- cant_inv_wide %>%
  mutate(
    cant_pos_inv_offset = cant_pos_inv_JDM - cant_pos_inv_M,
    cant_inv_offset = cant_inv_JDM - cant_inv_M,
    estimate = "JDM - M"
  )

# restrict to the standard inventory depth
cant_inv_long <- cant_inv_long %>%
  filter(inv_depth == params_global$inventory_depth_standard)

cant_inv_wide <- cant_inv_wide %>%
  filter(inv_depth == params_global$inventory_depth_standard)

```

```{r cant_pos_inventory_map, fig.asp=0.5, eval=FALSE}

#for (i_eras in unique(cant_inv_long$eras)) {
#  for (i_estimate in unique(cant_inv_long$estimate)) {

library(patchwork)
i_eras <- "1982-1999 --> 2000-2012"

df1 <-
  cant_inv_long %>% filter(estimate == unique(cant_inv_long$estimate)[1], eras == i_eras)
df2 <-
  cant_inv_long %>% filter(estimate == unique(cant_inv_long$estimate)[2], eras == i_eras)

var = "cant_pos_inv"
breaks <- c(0, 2, 4, 6, 8, 10, 12, 14, 16, Inf)
var <- sym(var)
breaks_n <- length(breaks) - 1

df1 <- df1 %>%
#  mutate(lon = if_else(lon > 180, lon - 360, lon)) %>%
  mutate(var_int = cut(!!var,
                       breaks,
                       right = FALSE))
df2 <- df2 %>%
#  mutate(lon = if_else(lon > 180, lon - 360, lon)) %>%
  mutate(var_int = cut(!!var,
                       breaks,
                       right = FALSE))

# for (i in (1:length(map[["layers"]][[1]][["data"]][["lon"]]))){
#   if (map[["layers"]][[1]][["data"]][["lon"]][i] > 180) {
#     map[["layers"]][[1]][["data"]][["lon"]][i] = map[["layers"]][[1]][["data"]][["lon"]][i] -360
#   }
#   
# }

section <- map +
  scale_fill_manual(values = p_gruber_rainbow(breaks_n),
                    drop = FALSE,
                    name = expression(atop(Delta * C["ant,pos"],
                                           (mol ~ m ^ {
                                             -2
                                           })))) +
  guides(fill = guide_colorsteps(barheight = unit(6, "cm")))

a <- section +
  geom_raster(data = df1,
              aes(lon, lat, fill = var_int)) +
  labs(subtitle = "eMLR reconstruction")

b <- section +
  geom_raster(data = df2,
              aes(lon, lat, fill = var_int)) +
  labs(subtitle = "Model truth")

a / b +
  plot_layout(guides = "collect")


#  }
  print(
    p_map_cant_inv_offset(
      cant_inv_wide %>% filter(eras == i_eras),
      "cant_pos_inv_offset",
      title_text = "",
      subtitle_text = "Offset"
    )
  )
#}

```


# Zonal mean sections

## Cant - positive only

```{r read_cant_zonal_file, eval=FALSE}

cant_zonal_JDM <-
  read_csv(paste(path_version_data,
                 "cant_zonal.csv",
                 sep = ""))

cant_zonal_JDM <- cant_zonal_JDM %>%
  select(lat,
         depth,
         eras,
         basin_AIP,
         gamma_mean,
         cant_mean,
         cant_pos_mean,
         cant_sd,
         cant_pos_sd)

cant_zonal_M <-
  read_csv(paste(path_version_data,
                  "cant_zonal_M", sep = ""))

```

```{r join_cant_zonal, eval=FALSE}

cant_zonal_JDM_gamma <- cant_zonal_JDM %>%
  select(lat, depth, eras, basin_AIP, gamma_mean)

cant_zonal_M <- left_join(cant_zonal_JDM_gamma, cant_zonal_M)

rm(cant_zonal_JDM_gamma)

# add estimate label
cant_zonal_long <- bind_rows(cant_zonal_JDM %>%  mutate(estimate = "JDM"),
                             cant_zonal_M %>%  mutate(estimate = "M"))

# pivot to wide format
cant_zonal_wide <- cant_zonal_long %>%
  pivot_wider(names_from = estimate, values_from = cant_mean:cant_pos_sd) %>%
  drop_na()

# calculate offset
cant_zonal_wide <- cant_zonal_wide %>%
  mutate(
    cant_pos_mean_offset = cant_pos_mean_JDM - cant_pos_mean_M,
    cant_mean_offset = cant_mean_JDM - cant_mean_M,
    estimate = "JDM - M"
  )

```

```{r cant_pos_zonal_mean_section, fig.asp=0.6, eval=FALSE}

library(patchwork)
i_eras <- "1982-1999 --> 2000-2012"
i_basin_AIP <- "Pacific"

# df1 <- cant_zonal_long %>%
#             filter(
#               basin_AIP == i_basin_AIP,
#               estimate == unique(cant_zonal_long$estimate)[1],
#               eras == i_eras
#             )
# 
# df2 <- cant_zonal_long %>%
#             filter(
#               basin_AIP == i_basin_AIP,
#               estimate == unique(cant_zonal_long$estimate)[2],
#               eras == i_eras
#             )
# 
# 
#            var = "cant_pos"
#            var_name = var
#            gamma = "gamma_mean"
#            drop_slabs = 1
#            breaks = params_global$breaks_cant_pos
#            legend_title = expression(atop(Delta * C[ant,pos],
#                                           (mu * mol ~ kg ^ {-1})))
#            title_text = "Zonal mean section"
#            subtitle_text = ""
#            slab_breaks <- params_local$slabs_Ind_Pac
# 
#     var <- sym(var)
#     gamma <- sym(gamma)
#     
#     breaks_n <- length(breaks) - 1
# 
#     geom_raster(data = df1,
#               aes(lon, lat, fill = var_int)) +
#     
#     # plot base section
#     section <-
#       guides(fill = guide_colorsteps(barheight = unit(8, "cm"))) +
#       scale_y_reverse() +
#       scale_x_continuous(breaks = seq(-100, 100, 20),
#                          limits = c(-85,85)) +
#         scale_fill_manual(values = p_gruber_rainbow(breaks_n),
#                           drop = FALSE,
#                           name = legend_title) +
#       geom_hline(yintercept = params_local$depth_min,
#                    col = "white",
#                    linetype = 2) +
#         geom_contour(aes(lat, depth, z = !!gamma),
#                      breaks = slab_breaks,
#                      col = "black") +
#         geom_text_contour(
#           aes(lat, depth, z = !!gamma),
#           breaks = slab_breaks,
#           col = "black",
#           skip = drop_slabs
#         )
# 
#     
#          ggplot() +
#     
# 
#       section <- section +
#         geom_contour_filled(aes(lat, depth, z = !!var),
#                             breaks = breaks) +
#         scale_fill_manual(values = p_gruber_rainbow(breaks_n),
#                           drop = FALSE,
#                           name = legend_title)
# 
# section <- section  +
#         geom_hline(yintercept = params_local$depth_min,
#                    col = "white",
#                    linetype = 2) +
#         geom_contour(aes(lat, depth, z = !!gamma),
#                      breaks = slab_breaks,
#                      col = "black") +
#         geom_text_contour(
#           aes(lat, depth, z = !!gamma),
#           breaks = slab_breaks,
#           col = "black",
#           skip = drop_slabs
#         )
# 
#     # cut surface water section
#     surface <-
#       section +
#       ggplot(df = df1) +
#       geom_contour_filled(aes(lat, depth, z = !!var),
#                             breaks = breaks) +
#       coord_cartesian(
#         expand = 0,
#         ylim = c(500, 0)
#       ) +
#       labs(y = "Depth (m)",
#            title = title_text,
#            subtitle = subtitle_text) +
#       theme(
#         axis.title.x = element_blank(),
#         axis.text.x = element_blank(),
#         axis.ticks.x = element_blank()
#       )
# 
#     # cut deep water section
#     deep <-
#       section +
#       coord_cartesian(
#         expand = 0,
#         ylim = c(params_global$plotting_depth, 500)
#       ) +
#       labs(x = expression(latitude~(degree*N)), y = "Depth (m)")
# 
# 
#     # combine surface and deep water section
#   a <- surface / deep +
#       plot_layout(guides = "collect")

    
    a <- p_section_zonal(
          df = cant_zonal_long %>%
            filter(
              basin_AIP == i_basin_AIP,
              estimate == unique(cant_zonal_long$estimate)[1],
              eras == i_eras
            ),
          var = "cant_pos_mean",
          title_text = "",
          subtitle_text = "eMLR reconstruction",
        )
    a
   
     b <- p_section_zonal(
          df = cant_zonal_long %>%
            filter(
              basin_AIP == i_basin_AIP,
              estimate == unique(cant_zonal_long$estimate)[2],
              eras == i_eras
            ),
          var = "cant_pos_mean",
          title_text = "",
          subtitle_text = "Model truth"
        )
    
     a + b +
  plot_layout(guides = "collect")
      
    
    # Offset
    print(
      p_section_zonal(
        df = cant_zonal_wide %>%
          filter(basin_AIP == i_basin_AIP,
                 eras == i_eras),
        var = "cant_pos_mean_offset",
        breaks = params_global$breaks_cant_offset,
        col = "divergent",
        title_text = "",
        subtitle_text = "Offset")
      )
    )



```



# Residual with latitude

```{r cant_residual_latitude}

b_cstar_tref <- function(df) {
  df <- df %>%
    mutate(cstar_tref_intercept = `coeff_(Intercept)`)
  
  vars = params_local$MLR_predictors
  
  for (i_var in vars) {
    df <- df %>%
      mutate(!!sym(paste("cstar_tref_", i_var, sep = "")) :=
               !!sym(i_var) *
               !!sym(paste("coeff_", i_var, sep = "")))
  }
  
  df <- df %>%
    select(-contains("coeff_"))
  
  df <- df %>%
    mutate(cstar_tref_fitted = reduce(select(., starts_with("cstar_tref_")), `+`))
  
  #df <- df %>%
  #  mutate(cant_pos = if_else(cant < 0, 0, cant))
  
  return(df)
  
}

lm_best_target <- read_csv(paste(path_version_data,
                                 "lm_best_target.csv",
                                 sep = ""))

GLODAP <-
  read_csv(paste(
    path_version_data,
    "GLODAPv2.2020_MLR_fitting_ready.csv",
    sep = ""
  ))

GLODAP <- GLODAP %>%
  select(
    lon,
    lat,
    depth,
    era,
    basin_AIP,
    basin,
    gamma,
    gamma_slab,
    sal,
    temp,
    aou,
    nitrate,
    silicate,
    phosphate,
    phosphate_star,
    cstar_tref
  )


# mutate predictors column
lm_best_plot <- lm_best_target %>%
  mutate(predictors = str_remove(model, paste(params_local$MLR_target, "~ ")),
         predictors = str_replace_all(predictors, "\\+ ", ""))

# loop across all basins, era, gamma slabs, and MLRs
# fit all MLR models
#  for (i_basin in unique(GLODAP$basin)) {
#    for (i_era in unique(GLODAP$era)) {
i_basin <- unique(GLODAP$basin)[2]
i_era   <- unique(GLODAP$era)[1]
print(i_basin)
print(i_era)

GLODAP_basin_era <- GLODAP %>%
  filter(basin == i_basin, era == i_era)

#      for (i_gamma_slab in unique(GLODAP_basin_era$gamma_slab)) {
i_gamma_slab <- unique(GLODAP_basin_era$gamma_slab)[4]
print(i_gamma_slab)

GLODAP_basin_era_slab <- GLODAP_basin_era %>%
  filter(gamma_slab == i_gamma_slab)

lm_best_basin_era_slab <- lm_best_plot %>%
  filter(basin == i_basin, era == i_era, gamma_slab == i_gamma_slab)

#       for (i_eras in unique(lm_best_basin_era_slab$eras)) {
i_eras <- unique(lm_best_basin_era_slab$eras)[1]
print(i_eras)

lm_best_basin_era_slab_eras <- lm_best_basin_era_slab %>%
  filter(eras == i_eras)

cstar_tref <-
  full_join(GLODAP_basin_era_slab, lm_best_basin_era_slab_eras)

#          for (i_predictors in unique(lm_best_basin_era_slab_eras$predictors)) {
i_predictors <-
  unique(lm_best_basin_era_slab$predictors)[1]
print(i_predictors)

cstar_tref <- b_cstar_tref(cstar_tref) %>%
  mutate(cstar_tref_residual = cstar_tref - cstar_tref_fitted)

residual <-
  ggplot(cstar_tref, aes(lat, cstar_tref_residual)) +
  geom_bin2d(binwidth = 1) +
  scale_fill_viridis_c(option = "magma",
                       direction = -1,
                       trans = "log10") +
  facet_wrap(~ predictors, ncol = 2) +
  labs(
    x = expression(latitude ~ (degree * N)),
    y = expression(C[t[ref]] ^ "*" ~ residual),
    subtitle = "Eras: 1982-1999 --> 2000-2012  Era: 1982-1999"
  )

ggsave(
  plot = residual,
  filename = "residual.png",
  width = 7,
  height = 9
)

  #           
  #         }
  #         
  #       }
  #       
  #     }
  #   }
  # }


```




