---
title: "Inventory maps"
author: "Jens Daniel Müller and Donghe Zhu"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r parent, child = "/nfs/kryo/work/jenmueller/emlr_cant/utilities/setup.Rmd"}
# this chunk runs the code stored in setup.Rmd
# if required, please refer to instructions given here:
# https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html
```

```{r read_params_local, include = FALSE}

Version_ID <- "v_XXX_101_Gruber"

```

```{r define_paths, include = FALSE}

path_model <-
  paste(path_root, "/model/", sep = "")

path_preprocessing    <-
  paste(path_model, "preprocessing/", sep = "")

params_local     <-
  read_rds(
    paste(
      "/home/donzhu/Thesis/emlr_cant/model/emlr_mod_v_XXX/data/auxillary/",
      "params_local.rds",
      sep = ""
    )
  )

path_version_data     <-
  paste(path_model,
        Version_ID,
        "/data/",
        sep = "")

path_version_figures  <-
  paste(path_model,
        Version_ID,
        "/figures/",
        sep = "")

```


```{r load_libraries_specific, include = FALSE}
library(scales)
library(marelac)
library(gt)
```

# Predictor correlation plots

```{r predictor_correlation_per_basin, fig.asp=1}

GLODAP <-
  read_csv(paste(path_version_data,
                 "GLODAPv2.2020_MLR_fitting_ready.csv",
                 sep = ""))

library(GGally)
library(plotly)
library(ggpubr)

for (i_basin in unique(GLODAP$basin)) {
 i_basin <- unique(GLODAP$basin)[2]

print(
GLODAP %>% 
  filter(basin == i_basin) %>% 
  sample_frac(0.05) %>%
  ggpairs(
    columns = c(
      params_local$MLR_target,
      "sal",
      "temp",
      "oxygen",
      "aou",
      "nitrate",
      "silicate",
      "silicate_star",
      "phosphate",
      "phosphate_star"
    ), 
    columnLabels = c("C[ref]*",
                  'Salinity',
                  'Temperature',
                  "Oxygen",
                  'AOU',
                  'Nitrate',
                  "Silicate",
                  "Silicate*",
                  "Phosphate",
                  "Phosphate*"),
  axisLabels="none",
    upper = "blank",
    ggplot2::aes(col = gamma_slab, fill = gamma_slab, alpha = 0.01)
  ) +
  scale_fill_viridis_d(direction = -1) +
  scale_color_viridis_d(direction = -1) +
  labs(title = paste(
    "Basin:",
    i_basin ,
    "| subsample size: 5 % of",
    nrow(GLODAP %>% filter(basin == i_basin)),
    "subset data"
  ))
)
}

##### Specific predictor pairs
a <- GLODAP %>%
  #filter(basin == i_basin) %>%
  sample_frac(0.05) %>%
  ggplot(aes(silicate, silicate_star, col = gamma_slab)) +
  geom_point() +
  scale_color_viridis_d(name = "Gamma slabs", direction = -1) +
  # theme(legend.key.size = unit(0.6, "cm"),
  #       legend.key.width = unit(0.5, "cm")) +
  guides(col = guide_legend()) +
  labs(x = expression(Silicate ~ (mu * mol ~ kg ^ {
         -1})),
       y = expression(Silicate * "*" ~ (mu * mol ~ kg ^ {
         -1}))
       )

b <- GLODAP %>%
  #filter(basin == i_basin) %>%
  sample_frac(0.05) %>%
  ggplot(aes(sal, temp, col = gamma_slab)) +
  geom_point() +
  scale_color_viridis_d(name = "Gamma slabs", direction = -1) +
  # theme(legend.key.size = unit(0.6, "cm"),
  #       legend.key.width = unit(0.5, "cm")) +
  guides(col = guide_legend()) +
  labs(x = "Salinity (g/kg)",
       y = "Temperature (°C)"
       )

c <- GLODAP %>%
  #filter(basin == i_basin) %>%
  sample_frac(0.05) %>%
  ggplot(aes(nitrate, phosphate, col = gamma_slab)) +
  geom_point() +
  scale_color_viridis_d(name = "Gamma slabs", direction = -1) +
  # theme(legend.key.size = unit(0.6, "cm"),
  #       legend.key.width = unit(0.5, "cm")) +
  guides(col = guide_legend()) +
  labs(x = expression(Nitrate ~ (mu * mol ~ kg ^ {
         -1})),
       y = expression(Phosphate ~ (mu * mol ~ kg ^ {
         -1}))
       )

d <- GLODAP %>%
  #filter(basin == i_basin) %>%
  sample_frac(0.05) %>%
  ggplot(aes(temp, phosphate_star, col = gamma_slab)) +
  geom_point() +
  scale_color_viridis_d(name = "Gamma slabs", direction = -1) +
  # theme(legend.key.size = unit(0.6, "cm"),
  #       legend.key.width = unit(0.5, "cm")) +
  guides(col = guide_legend()) +
  labs(x = "Temperature (°C)",
       y = expression(Phosphate * "*" ~ (mu * mol ~ kg ^ {
         -1
       })))

ggarrange(a, b, c, d, nrow = 2, ncol = 2, align = "hv", common.legend = TRUE, legend = "right")

ggsave("specific_correlation_pairs.png", width = 8, height = 6.6)

```


# AIC vs RMSE for all fitted models

```{r aic_vs_rmse}

path_version_data <- "/nfs/kryo/work/jenmueller/emlr_cant/model/v_XXX_118_my/data/"

lm_all_fitted_wide_eras %>% 
  write_csv(paste(path_version_data,
                  "lm_all_fitted_wide_eras.csv",
                  sep = ""))

lm_all_fitted_wide_eras %>% 
  filter(eras == unique(lm_all_fitted_wide_eras$eras)[1]) %>%
#  filter(basin == unique(lm_all_fitted_wide_eras$basin)[2]) %>%
  ggplot(aes(rmse, aic, col = gamma_slab)) +
  geom_point() +
  scale_color_viridis_d(direction = -1) +
  labs(
    x = expression(RMSE~(mu * mol ~ kg ^ {-1})),
    y = "AIC"
  ) +
  theme(
        legend.key.size = unit(0.45, "cm"),
        legend.key.width = unit(0.2,"cm")) +
  facet_grid(.~basin)

```


# Inventory maps

## Cant - positive only

```{r read_cant_inv_file, eval=FALSE}

cant_inv_JDM <-
  read_csv(paste(path_version_data,
                 "cant_inv.csv",
                 sep = ""))

cant_inv_M <-
  read_csv(paste(path_version_data,
                  "cant_inv_M.csv", sep = ""))

```

```{r join_M_and_JDM_inventories, eval=FALSE}

# add estimate label
cant_inv_long <- bind_rows(cant_inv_JDM %>%  mutate(estimate = "JDM"),
                           cant_inv_M %>%  mutate(estimate = "M"))

# pivot to wide format
cant_inv_wide <- cant_inv_long %>%
  pivot_wider(names_from = estimate, values_from = cant_pos_inv:cant_inv) %>%
  drop_na()

# calculate offset
cant_inv_wide <- cant_inv_wide %>%
  mutate(
    cant_pos_inv_offset = cant_pos_inv_JDM - cant_pos_inv_M,
    cant_inv_offset = cant_inv_JDM - cant_inv_M,
    estimate = "JDM - M"
  )

# restrict to the standard inventory depth
cant_inv_long <- cant_inv_long %>%
  filter(inv_depth == params_global$inventory_depth_standard)

cant_inv_wide <- cant_inv_wide %>%
  filter(inv_depth == params_global$inventory_depth_standard)

```

```{r cant_pos_inventory_map, fig.asp=0.5, eval=FALSE}

#for (i_eras in unique(cant_inv_long$eras)) {
#  for (i_estimate in unique(cant_inv_long$estimate)) {

i_eras <- "2000-2009 --> 2010-2019"
#i_eras <- "1982-1999 --> 2000-2009"

df1 <-
  cant_inv_long %>% filter(estimate == unique(cant_inv_long$estimate)[1], eras == i_eras)
df2 <-
  cant_inv_long %>% filter(estimate == unique(cant_inv_long$estimate)[2], eras == i_eras)

var = "cant_pos_inv"
breaks <- c(0, 2, 4, 6, 8, 10, Inf)
var <- sym(var)
breaks_n <- length(breaks) - 1

df1 <- df1 %>%
#  mutate(lon = if_else(lon > 180, lon - 360, lon)) %>%
  mutate(var_int = cut(!!var,
                       breaks,
                       right = FALSE))
df2 <- df2 %>%
#  mutate(lon = if_else(lon > 180, lon - 360, lon)) %>%
  mutate(var_int = cut(!!var,
                       breaks,
                       right = FALSE))

section <- map +
  scale_color_viridis_d() 
  # scale_fill_scico_d(palette = 'imola',
  #                    drop = FALSE,
  #                   name = expression(atop(Delta * C["ant,pos"],
  #                                         (mol ~ m ^ {
  #                                            -2
  #                                          })))) +
  # scale_fill_manual(values  = wes_palette("Zissou1", 7, type = "continuous"),
  #                   drop = FALSE,
  #                   name = expression(atop(Delta * C["ant,pos"],
  #                                         (mol ~ m ^ {
  #                                            -2
  #                                          })))) +
  # scale_fill_manual(values = p_gruber_rainbow(breaks_n),
  #                   drop = FALSE,
  #                   name = expression(atop(Delta * C["ant,pos"],
  #                                          (mol ~ m ^ {
  #                                            -2
  #                                          })))) +
  # guides(fill = guide_colorsteps(barheight = unit(4.5, "cm")))

a <- section +
  geom_raster(data = df1,
              aes(lon, lat, fill = var_int)) +
  labs(subtitle = "(a) eMLR reconstruction") 

a

b <- section +
  geom_raster(data = df2,
              aes(lon, lat, fill = var_int)) +
  labs(subtitle = "(b) Model truth") 

a / b +
  plot_layout(guides = "collect")

ggsave("2_Pac_inv.png")

########## Offset

breaks <- c(-Inf, -6, -4, -2, 0, 2, 4, 6, Inf)

section_o <- map +
  scale_fill_scico_d(palette = 'vik',
                    drop = FALSE,
                    name = expression(atop(Bias~Delta*C[ant],
                                                 (mol~m^{-2})))) +
  # scale_fill_manual(values=as.vector(ocean.balance(7)),
  #                   drop = FALSE,
  #                   name = expression(atop(Bias~Delta*C[ant],
  #                                                (mol~m^{-2})))) +
      # scale_fill_scico_d(palette = "vik", drop = FALSE,
      #                    name = expression(atop(Bias~Delta*C[ant],
      #                                           (mol~m^{-2})))) +
      guides(fill = guide_colorsteps(barheight = unit(4.5, "cm")))

c <- section_o +
  geom_raster(data = cant_inv_wide %>% filter(eras == i_eras),
                  aes(lon, lat, fill = cut(!!sym("cant_pos_inv_offset"), breaks))) +
  labs(subtitle = "(c) Bias")

c

d <- section_o +
  geom_raster(data = cant_inv_wide %>% filter(eras == i_eras),
                  aes(lon, lat, fill = cut(!!sym("cant_pos_inv_offset"), breaks))) +
  labs(subtitle = "(d) Bias - Constant & random subset")

c / d +
  plot_layout(guides = "collect")

ggsave("vg_inv_off.png")

```


# Zonal mean sections

## Cant - positive only

```{r read_cant_zonal_file, eval=FALSE}

cant_zonal_JDM <-
  read_csv(paste(path_version_data,
                 "cant_zonal.csv",
                 sep = ""))

cant_zonal_JDM <- cant_zonal_JDM %>%
  select(lat,
         depth,
         eras,
         basin_AIP,
         gamma_mean,
         cant_mean,
         cant_pos_mean,
         cant_sd,
         cant_pos_sd)

cant_zonal_M <-
  read_csv(paste(path_version_data,
                  "cant_zonal_M", sep = ""))

```

```{r join_cant_zonal, eval=FALSE}

cant_zonal_JDM_gamma <- cant_zonal_JDM %>%
  select(lat, depth, eras, basin_AIP, gamma_mean)

cant_zonal_M <- left_join(cant_zonal_JDM_gamma, cant_zonal_M)

rm(cant_zonal_JDM_gamma)

# add estimate label
cant_zonal_long <- bind_rows(cant_zonal_JDM %>%  mutate(estimate = "JDM"),
                             cant_zonal_M %>%  mutate(estimate = "M"))

# pivot to wide format
cant_zonal_wide <- cant_zonal_long %>%
  pivot_wider(names_from = estimate, values_from = cant_mean:cant_pos_sd) %>%
  drop_na()

# calculate offset
cant_zonal_wide <- cant_zonal_wide %>%
  mutate(
    cant_pos_mean_offset = cant_pos_mean_JDM - cant_pos_mean_M,
    cant_mean_offset = cant_mean_JDM - cant_mean_M,
    estimate = "JDM - M"
  )

```

```{r cant_pos_zonal_mean_section, fig.asp=0.6, eval=FALSE}

library(patchwork)
i_eras <- "2000-2009 --> 2010-2019"
#i_eras <- "1982-1999 --> 2000-2009"
i_basin_AIP <- "Pacific"

p_section_zonal <- function(df,
           var = "cant_pos",
           var_name = var,
           col = "continuous",
           gamma = "gamma_mean",
           plot_slabs = "y",
           drop_slabs = 1,
           breaks = c(0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,Inf),
           legend_title = expression(atop(Delta * C[ant,pos],
                                          (mu * mol ~ kg ^ {-1}))),
           subtitle_text = "") {

    var <- sym(var)
    gamma <- sym(gamma)

    # plot base section
    section <- df %>%
      ggplot() +
      guides(fill = guide_colorsteps(barheight = unit(8, "cm"))) +
      scale_y_reverse() +
      scale_x_continuous(breaks = seq(-100, 100, 20),
                         limits = c(-85,85))

    # plot layer for chose color scale (default continuous)
    if (col == "continuous") {

      breaks_n <- length(breaks) - 1

      section <- section +
        geom_contour_filled(aes(lat, depth, z = !!var),
                            breaks = breaks) +
        scale_fill_manual(values = p_gruber_rainbow(breaks_n),
                          drop = FALSE,
                          name = legend_title)
    } else {

      section <- section +
        geom_contour_filled(aes(lat, depth, z = !!var),
                            breaks = breaks) +
        scale_fill_scico_d(palette = "vik",
                           drop = FALSE,
                           name = legend_title)

    }


    # plot isoneutral density lines if chosen (default yes)
    if (plot_slabs == "y") {

      # select slab breaks for plotted basin
      if (i_basin_AIP == "Atlantic") {
        slab_breaks <- params_local$slabs_Atl
      } else {
        slab_breaks <- params_local$slabs_Ind_Pac
      }


      section <- section  +
        geom_hline(yintercept = params_local$depth_min,
                   col = "white",
                   linetype = 2) +
        geom_contour(aes(lat, depth, z = !!gamma),
                     breaks = slab_breaks,
                     col = "black") +
        geom_text_contour(
          aes(lat, depth, z = !!gamma),
          breaks = slab_breaks,
          col = "black",
          skip = drop_slabs
        )

    }

    # cut surface water section
    surface <-
      section +
      coord_cartesian(
        expand = 0,
        ylim = c(500, 0)
      ) +
      labs(y = "Depth (m)",
           subtitle = subtitle_text) +
      theme(
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()
      )

    # cut deep water section
    deep <-
      section +
      coord_cartesian(
        expand = 0,
        ylim = c(params_global$plotting_depth, 500)
      ) +
      labs(x = expression(latitude~(degree*N)), y = "Depth (m)")


    # combine surface and deep water section
    surface / deep +
      plot_layout(guides = "collect")

}
    
    a <- p_section_zonal(
          df = cant_zonal_long %>%
            filter(
              basin_AIP == i_basin_AIP,
              estimate == unique(cant_zonal_long$estimate)[1],
              eras == i_eras
            ),
          var = "cant_pos_mean",
          subtitle_text = "(a) eMLR reconstruction",
        )
    a
    
    ggsave("2_Pac_zon_em.png", width = 6.33, height =  4.54)
   
     b <- p_section_zonal(
          df = cant_zonal_long %>%
            filter(
              basin_AIP == i_basin_AIP,
              estimate == unique(cant_zonal_long$estimate)[2],
              eras == i_eras
            ),
          var = "cant_pos_mean",
          subtitle_text = "(b) Model truth"
        )
    
     b
     
     ggsave("2_Pac_zon_mo.png", width = 6.33, height =  4.54)
     
########### Offset
      p_section_zonal(
        df = cant_zonal_wide %>%
          filter(basin_AIP == i_basin_AIP,
                 eras == i_eras),
        var = "cant_pos_mean_offset",
        breaks = params_global$breaks_cant_offset,
        col = "divergent",
        subtitle_text = "(c) Bias")
      
      ggsave("so_Pac_zon_off.png", width = 6.33, height =  4.54)

```



# Residual with latitude

```{r cant_residual_latitude, eval=FALSE}

b_cstar_tref <- function(df) {
  df <- df %>%
    mutate(cstar_tref_intercept = `coeff_(Intercept)`)
  
  vars = params_local$MLR_predictors
  
  for (i_var in vars) {
    df <- df %>%
      mutate(!!sym(paste("cstar_tref_", i_var, sep = "")) :=
               !!sym(i_var) *
               !!sym(paste("coeff_", i_var, sep = "")))
  }
  
  df <- df %>%
    select(-contains("coeff_"))
  
  df <- df %>%
    mutate(cstar_tref_fitted = reduce(select(., starts_with("cstar_tref_")), `+`))
  
  #df <- df %>%
  #  mutate(cant_pos = if_else(cant < 0, 0, cant))
  
  return(df)
  
}

lm_best_target <- read_csv(paste(path_version_data,
                                 "lm_best_target.csv",
                                 sep = ""))

GLODAP <-
  read_csv(paste(
    path_version_data,
    "GLODAPv2.2020_MLR_fitting_ready.csv",
    sep = ""
  ))

GLODAP <- GLODAP %>%
  select(
    lon,
    lat,
    depth,
    era,
    basin_AIP,
    basin,
    gamma,
    gamma_slab,
    sal,
    temp,
    aou,
    oxygen,
   # nitrate,
    silicate,
    phosphate,
    phosphate_star,
    cstar_tref
  )

# mutate predictors column
lm_best_plot <- lm_best_target %>%
  mutate(predictors = str_remove(model, paste(params_local$MLR_target, "~ ")),
         predictors = str_replace_all(predictors, "\\+ ", ""))

# loop across all basins, era, gamma slabs, and MLRs
# fit all MLR models
#  for (i_basin in unique(GLODAP$basin)) {
#    for (i_era in unique(GLODAP$era)) {
#i_basin <- unique(GLODAP$basin)[2]
i_basin <- c("Indo-Pacific", "SO")
i_era   <- unique(GLODAP$era)[3]
#i_era   <- c("1982-1999", "2000-2012")
print(i_basin)
print(i_era)

GLODAP_basin_era <- GLODAP %>%
  filter(basin == i_basin, era == i_era)

#      for (i_gamma_slab in unique(GLODAP_basin_era$gamma_slab)) {
i_gamma_slab <- unique(GLODAP_basin_era$gamma_slab)[7]
print(i_gamma_slab)

GLODAP_basin_era_slab <- GLODAP_basin_era %>%
  filter(gamma_slab == i_gamma_slab)

lm_best_basin_era_slab <- lm_best_plot %>%
  filter(basin %in% i_basin, era == i_era, gamma_slab == i_gamma_slab)

#       for (i_eras in unique(lm_best_basin_era_slab$eras)) {
i_eras <- unique(lm_best_basin_era_slab$eras)[1]
print(i_eras)

lm_best_basin_era_slab_eras <- lm_best_basin_era_slab %>%
  filter(eras == i_eras)

cstar_tref <-
  full_join(GLODAP_basin_era_slab, lm_best_basin_era_slab_eras)

#          for (i_predictors in unique(lm_best_basin_era_slab_eras$predictors)) {
i_predictors <-
  unique(lm_best_basin_era_slab$predictors)[1]
print(i_predictors)

cstar_tref <- b_cstar_tref(cstar_tref) %>%
  mutate(cstar_tref_residual = cstar_tref - cstar_tref_fitted) %>%
  select(-basin)

print(
  ggplot(cstar_tref, aes(lat, cstar_tref_residual)) +
    geom_bin2d(binwidth = 1) +
    scale_fill_viridis_c(
      option = "magma",
      direction = -1,
      trans = "log10"
    ) +
    ylim(-15, 15) +
    geom_vline(xintercept = -35) +
    # facet_wrap(~ predictors, ncol = 2) +
    labs(
      x = expression(latitude ~ (degree * N)),
      y = expression(C[t[ref]] ^ "*" ~ residual),
      #subtitle = "(c) Era: 1982-1999"
      subtitle = "(d) Era: 2000-2009"
    )
)

ggsave("residual_e2_rso.png")

# calculate mean residual -35~-40
cstar_tref1 <- cstar_tref %>%
  filter(lat >= -40) %>%
  filter(lat <= -25) 

mean(cstar_tref1$cstar_tref_residual)

# ggsave(
#   plot = residual,
#   filename = "residual.png",
#   width = 7,
#   height = 9
# )

  #           
  #         }
  #         
  #       }
  #       
  #     }
  #   }
  # }

```

```{r delta_cant_rmse, eval=FALSE}

b_cstar_tref <- function(df) {
  df <- df %>%
    mutate(cstar_tref_intercept = `coeff_(Intercept)`)
  
  vars = params_local$MLR_predictors
  
  for (i_var in vars) {
    df <- df %>%
      mutate(!!sym(paste("cstar_tref_", i_var, sep = "")) :=
               !!sym(i_var) *
               !!sym(paste("coeff_", i_var, sep = "")))
  }
  
  df <- df %>%
    select(-contains("coeff_"))
  
  df <- df %>%
    mutate(cstar_tref_fitted = reduce(select(., starts_with("cstar_tref_")), `+`))
  
  #df <- df %>%
  #  mutate(cant_pos = if_else(cant < 0, 0, cant))
  
  return(df)
  
}

lm_best_target <- read_csv(paste(path_version_data,
                                 "lm_best_target.csv",
                                 sep = ""))

GLODAP <-
  read_csv(paste(
    path_version_data,
    "GLODAPv2.2020_MLR_fitting_ready.csv",
    sep = ""
  ))

GLODAP <- GLODAP %>%
  select(
    lon,
    lat,
    depth,
    era,
    basin_AIP,
    basin,
    gamma,
    gamma_slab,
    sal,
    temp,
    aou,
    oxygen,
   # nitrate,
    silicate,
    phosphate,
    phosphate_star,
    cstar_tref
  )

lm_best <-
  read_csv(paste(path_version_data,
                  "lm_best.csv",
                  sep = "")) %>%
  select(basin, gamma_slab, eras, model, rmse, rmse_sum)

lm_best_target <- left_join(lm_best_target, lm_best)

lm_best_target <- lm_best_target %>%
  mutate(rmse = case_when(eras == "1982-1999 --> 2000-2009" & era == "1982-1999" ~ rmse_sum - rmse,
                          eras == "1982-1999 --> 2000-2009" & era == "2000-2009" ~ rmse,
                          eras == "2000-2009 --> 2010-2019" & era == "2000-2009" ~ rmse_sum - rmse,
                          eras == "2000-2009 --> 2010-2019" & era == "2010-2019" ~ rmse))

# mutate predictors column
lm_best_plot <- lm_best_target %>%
  mutate(predictors = str_remove(model, paste(params_local$MLR_target, "~ ")),
         predictors = str_replace_all(predictors, "\\+ ", ""))

# loop across all basins, era, gamma slabs, and MLRs
# fit all MLR models
#  for (i_basin in unique(GLODAP$basin)) {
#    for (i_era in unique(GLODAP$era)) {
i_basin <- unique(GLODAP$basin)[2]
i_era   <- unique(GLODAP$era)[3]
print(i_basin)
print(i_era)

GLODAP_basin_era <- GLODAP %>%
  filter(basin == i_basin, era == i_era)

#      for (i_gamma_slab in unique(GLODAP_basin_era$gamma_slab)) {
i_gamma_slab <- unique(GLODAP_basin_era$gamma_slab)[4]
print(i_gamma_slab)

GLODAP_basin_era_slab <- GLODAP_basin_era %>%
  filter(gamma_slab == i_gamma_slab)

lm_best_basin_era_slab <- lm_best_plot %>%
  filter(basin == i_basin, era == i_era, gamma_slab == i_gamma_slab)

#       for (i_eras in unique(lm_best_basin_era_slab$eras)) {
i_eras <- unique(lm_best_basin_era_slab$eras)[1]
print(i_eras)

lm_best_basin_era_slab_eras <- lm_best_basin_era_slab %>%
  filter(eras == i_eras)

cstar_tref <-
  full_join(GLODAP_basin_era_slab, lm_best_basin_era_slab_eras)

#          for (i_predictors in unique(lm_best_basin_era_slab_eras$predictors)) {
# i_predictors <-
#   unique(lm_best_basin_era_slab$predictors)[1]
# print(i_predictors)

cstar_tref <- b_cstar_tref(cstar_tref) %>%
  mutate(cstar_tref_residual = cstar_tref - cstar_tref_fitted)

cstar_tref <- cstar_tref %>%
  filter(lat >= -40) %>%
  filter(lat <= -25) 

cstar_tref[,'rmse']=round(cstar_tref[,'rmse'], 3)

cstar_tref %>%
  ggplot(aes(as.factor(rmse),
             cstar_tref_residual)) +
  geom_boxplot(fill = "#5499C7") +
  labs(#subtitle = "(a) Era: 1982-1999",
       subtitle = "(b) Era: 2000-2009",
       x = expression(RMSE ~ 
                        (mu * mol ~ kg ^ {
         -1})),
       y = expression(C[t[ref]] ^ "*" ~ residual~ (mu * mol ~ kg ^ {
         -1})))

ggsave("ref_res_rmse_e2.png")


#red: #CD6155
#blue: #5499C7

# ggsave(
#   plot = residual,
#   filename = "residual.png",
#   width = 7,
#   height = 9
# )

  #           
  #         }
  #         
  #       }
  #       
  #     }
  #   }
  # }


```

```{r bias_rmse}

# read in required files
predictors <-
  read_csv(paste(path_version_data,
                 "predictors_M2007.csv",
                 sep = ""))

# calculate mean rmse and aic for each eras
lm_best <-
  read_csv(paste(path_version_data,
                 "lm_best.csv",
                 sep = "")) %>%
  mutate(rmse_mean = rmse_sum / 2,
         aic_mean = aic_sum / 2) %>%
  select(basin, gamma_slab, eras, model, rmse_mean, aic_mean)

lm_best_cant <-
  read_csv(paste(path_version_data,
                 "lm_best_cant.csv",
                 sep = ""))

# join predictors and MLR
cant <- full_join(predictors, lm_best_cant)

cant <- b_cant(cant)

cant_M <-
  read_csv(paste(path_version_data,
                 "cant_M.csv", sep = ""))

cant_M <- cant_M %>%
  rename(cant_M = cant, cant_pos_M = cant_pos)

cant_join <- left_join(cant, cant_M) %>%
  mutate(cant_offset = cant - cant_M,
         cant_pos_offset = cant_pos - cant_pos_M) %>%
  select(lon, lat, basin, gamma_slab, eras, model, depth, cant_pos_offset)

cant_bias <- left_join(cant_join, lm_best)

rm(cant_join, cant, cant_M, lm_best, lm_best_cant, predictors)
  
library(tibble)
depth_level_volume <- tibble(depth = unique(cant_bias$depth)) %>%
  arrange(depth)

# determine depth level volume of each depth layer
depth_level_volume <- depth_level_volume %>%
  mutate(
    layer_thickness_above = replace_na((depth - lag(depth)) / 2, 0),
    layer_thickness_below = replace_na((lead(depth) - depth) / 2, 0),
    layer_thickness = layer_thickness_above + layer_thickness_below
  ) %>%
  select(-c(layer_thickness_above,
            layer_thickness_below))

cant_bias <- full_join(cant_bias, depth_level_volume)

# calculate cant grid bias
cant_bias <- cant_bias %>%
  mutate(
    surface_area = earth_surf(lat, lon),
    cant_pos_bias_grid = cant_pos_offset * layer_thickness * 1.03 * 1000 * surface_area * 12 * 1e-15 * 1e-6
  ) %>%
  select(-layer_thickness, -surface_area)

cant_bias_slab <- cant_bias %>%
  group_by(eras, basin, gamma_slab, model, rmse_mean, aic_mean) %>%
  summarise(cant_pos_bias = sum(cant_pos_bias_grid)) %>%
  ungroup()

# plot for bias with rmse
ggplot(data = cant_bias_slab,
       aes(rmse_mean, cant_pos_bias, col = gamma_slab)) +
  geom_point() +
  scale_color_viridis_d(name = "Gamma slabs") +
  guides(col = guide_legend(ncol = 2)) +
  theme(legend.title = element_text(size = 9),
        legend.text = element_text(size = 6.5),
    legend.position = c(0.84, 0.81),
        legend.key.size = unit(0.3, "cm"),
        legend.key.width = unit(0.2,"cm"),
        legend.background = element_rect(fill = "lightgray")) +
  xlim(0, 7) +
#  ylim(0, 1) +
  facet_grid(basin ~ eras) +
  labs(
    x = expression(RMSE ~ (mu * mol ~ kg ^ "-1")),
    y = "Bias (Pg C)"
  )

# sum of all mean bias for each slab and basin
cant_bias_slab_mean <- cant_bias_slab %>%
  group_by(eras, basin, gamma_slab) %>%
  summarise(cant_pos_bias_mean = mean(cant_pos_bias)) %>%
  ungroup()

cant_bias_slab_mean_sum <- cant_bias_slab_mean %>%
  group_by(eras) %>%
  summarise(cant_pos_bias_mean_sum = sum(cant_pos_bias_mean)) %>%
  ungroup()
#### The sum of mean bias is smaller than the carbon budget calculations

# plot for bias with AIC
ggplot(data = cant_bias_slab,
       aes(aic_mean, cant_pos_bias, col = gamma_slab)) +
  geom_point() +
  scale_color_viridis_d(name = "Gamma slabs") +
  guides(col = guide_legend(ncol = 2)) +
  theme(legend.title = element_text(size = 9),
        legend.text = element_text(size = 6.5),
    legend.position = c(0.84, 0.81),
        legend.key.size = unit(0.3, "cm"),
        legend.key.width = unit(0.2,"cm"),
        legend.background = element_rect(fill = "lightgray")) +
  xlim(0, 60000) +
#  ylim(0, 1) +
  facet_grid(basin ~ eras) +
  labs(
    x = "AIC",
    y = "Bias (Pg C)"
  )

```

